version: '3.7'

services:
  powershell:
    image: mcr.microsoft.com/powershell
    container_name: powershell
    volumes:
      - ./scripts:/scripts
      - ./upload:/tmp
    entrypoint: powershell.exe -ExecutionPolicy Bypass -File /scripts/8800SX.ps1
    networks:
      - backend

  web:
    image: nginx:latest
    container_name: web
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./data/web:/var/www/html
      - ./data/config/nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      - backend
      - frontend

  php-fpm:
    image: php:8.2-fpm
    container_name: php8.2
    volumes:
      - ./app:/var/www/html
    networks:
      - backend
      - frontend

  db:
    image: mysql
    container_name: db
    restart: always
    volumes: 
      - ./db/data:/var/lib/mysql
      - ./db/logs:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Password
    restart: always
    ports:
      - 8888:80
    networks:
      - backend
  
  tinyfilemanager:
    image: tinyfilemanager/tinyfilemanager:master
    container_name: tinyfilemanager
    restart: always
    volumes:
      - ./scripts/upload:/var/www/html/data
    ports:
      - 8088:80
    networks:
      - backend
            
networks:
  frontend:
    driver: bridge         
  backend:
    driver: bridge
