version: '3.7'

services:

  web:
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - php-fpm
    ports:
      - 8080:80
    volumes:
      - ./data/web:/var/www/html
      - ./data/web/config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  php-fpm:
    image: php:8.2-fpm
    container_name: php8.2
    volumes:
      - ./data/web:/var/www/html
    networks:
      - backend

  db:
    image: mysql
    container_name: db
    restart: always
    volumes: 
      - ./data/db/data:/var/lib/mysql
      - ./data/db/logs:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ChangeThisOnlS7bBCb
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
    ports:
      - 8888:80
    networks:
      - backend
  
  tinyfilemanager:
    image: tinyfilemanager/tinyfilemanager:master
    container_name: tinyfilemanager
    restart: always
    depends_on:
      - web
    volumes:
      - ./data/web/upload/uploadfolder/upload:/var/www/html/uploadfolder/upload
    ports:
      - 8088:80
    networks:
      - backend
        
networks:
  backend:
    driver: bridge
