version: '3.7'

services:

  web:
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - php-fpm
    ports:
      - 8080:80
    volumes:
      - ./data/web:/var/www/html
      - ./data/web/uploads:/var/www/html/uploads
      - ./data/web/config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  php-fpm:
    container_name: php8.2
    # Dockerfile path
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/web:/var/www/html
    networks:
      - backend

  db:
    image: mysql
    container_name: db
    restart: always
    volumes: 
      - ./data/db/data:/var/lib/mysql
      - ./data/db/logs:/var/log/mysql
      - ./data/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: viavi
      MYSQL_USER: viavi
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
    ports:
      - 8888:80
    networks:
      - backend

secrets:
   db_root_password:
     file: ./secret/db_root_password.txt
   db_password:
     file: ./secret/db_password.txt

networks:
  backend:
    driver: bridge
