name: 8800sx

services:
  web:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
    volumes:
      - ./data/web:/var/www/html:ro
      - ./data/web/uploads:/var/www/html/uploads:rw
      - ./data/web/config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  php-fpm:
    container_name: php8.3
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./data/web:/var/www/html:rw
      - ./data/web/uploads:/var/www/html/uploads:rw
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "php-fpm -t"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.4
    container_name: mysql-db
    restart: unless-stopped
    volumes: 
      - db_data:/var/lib/mysql
      - mysql_logs:/var/log/mysql
      - ./data/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: viavi
      MYSQL_USER: viavi
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:
    driver: local
  mysql_logs:
    driver: local

secrets:
  db_password:
    file: ./secrets/db_password.txt

networks:
  backend:
    driver: bridge
