services:

  web:
    image: nginx
    container_name: viavi-web
    restart: always
    depends_on:
      - php-fpm
    ports:
      - 8080:80
    volumes:
      - ./data/web:/var/www/html
      - ./data/web/uploads:/var/www/html/uploads
      - ./data/web/nginx.conf:/etc/nginx/conf.d/default.conf
    # Only use this block with Traefik set up
    #labels:
    #  # Enable Traefik for this service
    #  - "traefik.enable=true"
    #  # Specify the network Traefik should use
    #  - "traefik.docker.network=traefik"
    #  # HTTP Router
    #  - "traefik.http.routers.viavi.rule=Host(`viavi.example.com`)"
    #  - "traefik.http.routers.viavi.entrypoints=web"
    #  # HTTPS Router (with automatic redirect)
    #  - "traefik.http.routers.viavi-secure.rule=Host(`viavi.example.com`)"
    #  - "traefik.http.routers.viavi-secure.entrypoints=websecure"
    #  - "traefik.http.routers.viavi-secure.tls=true"
    #  - "traefik.http.routers.viavi-secure.tls.certresolver=letsencrypt"
    #  # Middleware for HTTP to HTTPS redirect
    #  - "traefik.http.middlewares.viavi-redirect.redirectscheme.scheme=https"
    #  - "traefik.http.middlewares.viavi-redirect.redirectscheme.permanent=true"
    #  - "traefik.http.routers.viavi.middlewares=viavi-redirect"
    #  # Service (tell Traefik which port to use)
    #  - "traefik.http.services.viavi.loadbalancer.server.port=80"
    networks:
      #- traefik  # Only use this block with Traefik set up
      - viavi

  php-fpm:
    container_name: viavi-php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/web:/var/www/html
      - ./data/web/uploads:/var/www/html/uploads
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    networks:
      - viavi

  db:
    image: mysql:8.4.2
    container_name: viavi-db
    restart: always
    volumes: 
      - ./data/db/data:/var/lib/mysql
      - ./data/db/logs:/var/log/mysql
      - ./data/db/init/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: viavi
      MYSQL_USER: viavi
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    networks:
      - viavi

secrets:
   db_password:
     file: ./secrets/db_password.txt

networks:
  viavi:
    driver: bridge
