services:

  web:
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - php-fpm
    ports:
      - 8080:80
    volumes:
      - ./data/web:/var/www/html
      - ./data/web/uploads:/var/www/html/uploads
      - ./data/web/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  php-fpm:
    container_name: php8.2
    # Dockerfile path
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/web:/var/www/html
      - ./data/web/uploads:/var/www/html/uploads
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    networks:
      - backend

  db:
    image: mysql:8.4.2
    container_name: db
    restart: always
    volumes: 
      - ./data/db/data:/var/lib/mysql
      - ./data/db/logs:/var/log/mysql
      - ./data/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: viavi
      MYSQL_USER: viavi
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    networks:
      - backend

secrets:
   db_password:
     file: ./secrets/db_password.txt

networks:
  backend:
    driver: bridge
